# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoDaoOrig',
            fields=[
                ('intid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('subtitle', models.TextField()),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(max_length=128)),
                ('studio', models.CharField(blank=True, max_length=128, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('rating', models.CharField(max_length=128)),
                ('inetref', models.CharField(max_length=255)),
                ('collectionref', models.IntegerField()),
                ('homepage', models.TextField()),
                ('year', models.IntegerField()),
                ('releasedate', models.DateField()),
                ('userrating', models.FloatField()),
                ('length', models.IntegerField()),
                ('playcount', models.IntegerField()),
                ('season', models.SmallIntegerField()),
                ('episode', models.SmallIntegerField()),
                ('showlevel', models.IntegerField()),
                ('filename', models.TextField()),
                ('hash', models.CharField(max_length=128)),
                ('coverfile', models.TextField()),
                ('childid', models.IntegerField()),
                ('browse', models.IntegerField()),
                ('watched', models.IntegerField()),
                ('processed', models.IntegerField()),
                ('playcommand', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.IntegerField()),
                ('trailer', models.TextField(blank=True, null=True)),
                ('host', models.TextField()),
                ('screenshot', models.TextField(blank=True, null=True)),
                ('banner', models.TextField(blank=True, null=True)),
                ('fanart', models.TextField(blank=True, null=True)),
                ('insertdate', models.DateTimeField(blank=True, null=True)),
                ('contenttype', models.CharField(max_length=43)),
            ],
            options={
                'managed': False,
                'db_table': 'videometadata',
            },
        ),
    ]
